CXX=g++
CXXFLAGS = -Wall -std=c++11

all: 1 2 3 4 5 6 7 8 
1: 1.cpp bankaccount.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
2: 2.cpp person.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
3: 3.cpp golf.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
4: 4.cpp sales.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
5: 5.cpp stack.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
6: 6.cpp move.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@	
7: 7.cpp plorg.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
8: 8.cpp list.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
clean:
	rm -f *.exe