CXX=g++
CXXFLAGS = -Wall

all: 1 2 3 4 5 6 7
1: 1.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
2: 2.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
3: 3.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
4: 4.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
5: 5.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
6: 6.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@	
7: 7.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
clean:
	rm -f *.exe