CXX=g++
CXXFLAGS = -Wall -std=c++11

all: 1 2 3 4 5 6 7
1: 1.cpp vect.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
2: 2.cpp vect02.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
3: 3.cpp vect.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
4: 4.cpp mytime3.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
5: 5.cpp stonewt.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
6: 6.cpp stonewt.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@	
7: 7.cpp complex0.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
clean:
	rm -f *.exe *.txt