CXX=g++
CXXFLAGS = -Wall -std=c++11

all: 1 2 3 4 5 6 7 8 9 10 
1: 1.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
2: 2.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
3: 3.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
4: 4.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
5: 5.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
6: 6.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@	
7: 7.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
8: 8.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
9: 9.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
10: 10.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@
clean:
	rm -f *.exe